
label_format: camvid                  # images_only | yolo_det_1_0 | camvid | coco1.0 
class_names: 
  - "zoysia"
project_id: 314175
task_id: 1628875
image_quality: 100            # 0-100, only for images_only

detect:
  train_project_name: zoysia
  cvat_project_name: # Use this for new projects
  project_id: # Use this if the project already exists
  task_name: # Use this for new tasks
  task_id: # Use this if the task already exists
  
  importer:
    root_dir: ${paths.workdir}/data/batches/NC_2025-09-22/cropped/20deg
    project_id: 314175      # ID of the project to create or ID of the existing project
    task_name: NC_2025-09-22_20deg  # Name of the task to create or ID of the existing task
    label_format: Coco        # yolo_det_1_0 | coco1.0
    include_images: true       # include images when importing annotations
    images_quality: 100       # 0-100, only for images_only
    update: false
    label_map:
      0: zoysia
                    # update existing annotations

  export:
    out_dir: cvat_export/spring_2026_esleyther_zoysia
    task_id: 2311643         # ID of the task to export from
    label_format: yolo       # yolo_det_1_0 | coco1.0
    save_images: false        # save images with annotations
    save_images_quality: 100   # 0-100, only for images
