# train_config.yaml
# ---- model & run metadata ----
model: yolo11m.pt          # any Ultralytics model: yolov8[n|s|m|l|x].pt or a custom .pt
project: runs/train        # parent output directory
name: exp                  # run name (subfolder)
exist_ok: false             # allow overwrite of existing run folder

# Subdirectory stem for saving results; actual dir will have an incrementing suffix
save_subdir_stem: semif_NC_2025-09-12_iou0.55_conf0.55_post_fusion_nms_labeled
# save_dir: ${paths.workdir}/runs/inference/${evaluate.save_subdir_stem}  # path to save results
save_dir: ${paths.workdir}/data/batches/NC_2025-09-19/cropped/20deg/labels

model_dir: ${paths.workdir}/runs/  # path to model for inference
custom_path: ${evaluate.model_dir}/train/mixed_test_dataset/weights/last.pt  # path to model for inference
source_dir: ${paths.workdir}/data/batches/NC_2025-09-19/cropped/20deg/images  # path to images for inference

split: test #val
save_json: true
run_version: 1 # looks in runs_1; is ignored if custom_path is provided

# Device selection
device: auto

# Base image size used for scale factors below
base_imgsz: 2000

# Multiscale inference scales
scales: [0.15, 0.25, 0.5, 1.0, 1.25, 1.5]

# Per-scale filtering 
per_scale_conf: 0.0
per_scale_iou: 1.0
per_scale_max_det: 2000

# Final postprocess thresholds (single NMS after concatenation)
# These map to Ultralytics' conf/iou
conf: 0.35           # final_conf
iou: 0.55           # final_iou
final_max_det: 2000

# Optional extra NMS right after WBF (before Ultralytics NMS)
post_fusion_nms:
  enabled: true   # set true to turn it on
  iou: 0.30        # IoU threshold for batched_nms

# Inference
save_txt: true      # save results to *.txt (saves in ${evaluate.save_dir}/labels)

# Visualization
save_crops: false
draw_labels: true
draw_boxes: true
draw_conf: true
line_width: 1.5
font_size: .15

# --- label-based evaluation ---
viz_single_image_preds: true  # save predicted images with boxes to save_dir/preds
eval_labels:
  enabled: false              # required
  iou_thresholds: [0.50, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]     # or [0.50,0.55,...,0.95] for COCO-style mAP
  per_image: true           # true = also log per-image precision/recall
  labels_dir: null
  save_json: true            # write metrics JSON next to the images/ folder
  viz_side_by_side: 
    enabled: true # Save side-by-side GT and Pred images with TP/FP/FN coloring
    save_full_res: false # If true, saves full resolution images; longer but higher quality
    save_preview: true # If true, saves preview; faster but lower quality


# Optional class name map (use model.names if null)
names: #null
  0: seed_head

# GPU policy for AUTO picker (logical indices after CUDA_VISIBLE_DEVICES)
gpus:
  n: 4
  exclude_id: 0

# NMS backend (kept for parity with your other evaluate tasks)
nms_method: ultralytics