workdir: ${hydra:runtime.cwd}  # where the code is executed
log_dir: ${paths.workdir}/.logs
data_dir: ${paths.workdir}/data

batches_dir: ${paths.data_dir}/batches
batch_dir: ${paths.batches_dir}/${batch_id}

cropped_data_dir: ${paths.batch_dir}/cropped
initial_masks_dir: ${paths.batch_dir}/initial_masks

weights_dir: ${paths.data_dir}/weights
sam2_weights: ${paths.weights_dir}/sam2/checkpoints/sam2.1_hiera_large.pt
sam2_config: /${paths.weights_dir}/sam2/configs/sam2.1_hiera_l.yaml

lts_locations:
  - /mnt/research-projects/s/screberg/longterm_images
  - /mnt/research-projects/s/screberg/GROW_DATA
  - /mnt/research-projects/s/screberg/longterm_images2

# Species info
lts_species_info: /mnt/research-projects/s/screberg/longterm_images2/semifield-utils/species_information/species_info.json 

key_path: ${paths.workdir}/.keys/keys.yaml

train_cfg: ${hydra:runtime.cwd}/train_projects/zoysia_mixed/dataset.yaml